### ISSUE TITLE
你好，能做app广播和服务检测不

### ISSUE THREAD

**Issue by kittyzero520** [gaojingwen945/Xposed#1]
比如说
1.APP怎么自启动了
2.APP被其它APP通过sdk或广播唤醒了
3.APP什么时候拿了什么字段数据或权限

**Comment by gaojingwen945** [comment]
不好意思，十一休假了，没看到🤣
1、2应该可以调研下看看是否可以找到对应的hook入口，能找到hook入口就可以做到，
3描述有点模糊了。

**Comment by kittyzero520** [comment]
你好，我想花钱支撑你继续学习下去，我需要分析app中的问题，支撑行业监管

**Comment by gaojingwen945** [comment]
不知道我直接回复的邮件消息是不是没发出去。。 感谢认可~ 请问你这边具体需求是啥？我可以先看看~

**Comment by kittyzero520** [comment]
1.获取app运行中申请系统的权限（权限名称、申请时间）
2.app进程杀死后，自启情况（启动时间、启动进程、启动方式（sdk唤醒、广播唤醒等））、频繁自启
3.app运行中产生的数据（https、http、tcp、udp等）

**Comment by gaojingwen945** [comment]
是你自己有源码的app吗？如果没有的话得先看下是否可以在VirtualXposed中打开，能打开才能往后走下一步。
1. 应该好做；
2. 需要调研；
3. 原始数据？需要调研。

**Comment by kittyzero520** [comment]
你有应届生还是毕业生，可以加上联系方式，详细聊下

**Comment by gaojingwen945** [comment]
好，那你给我个邮箱吧？

**Comment by kittyzero520** [comment]
kittyzero@vip.qq.com

**Comment by gaojingwen945** [comment]
已用3412开头的QQ邮箱回复，请查收哈
